// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Maps: typeof import('./src/components/Maps/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider/slider.vue')['default']
    SliderItem: typeof import('./src/components/Slider/slider-item.vue')['default']
    Swiper: typeof import('./src/components/Swiper/index.vue')['default']
  }
}
